apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Admin API Metrics
    type: prometheus
    access: proxy
    url: http://host.docker.internal:8000
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      timeInterval: 10s
